version: "3"

services:
  web:
    build: .
    ports:
      - 8080:8080

  web1:
    build: .
    ports:
      - 8081:8080

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - mongodb-data:/bitnami/mongodb

volumes:
  mongodb-data:
